name: dry-configurable
codacy_id: 0276a97990e04eb0ac722b3e7f3620b5
gemspec:
  authors: ["Andy Holland"]
  email: ["andyholland1991@aol.com"]
  summary: "A mixin to add configuration functionality to your classes"
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [zeitwerk, "~> 2.6"]
    - [dry-core, "~> 0.6"]
